Logging started at 17:00:37 on 07 Mar 2014
QIIME version: 1.7.0

qiime_config values:
template_alignment_lanemask_fp	/home/db/blastdb/qiime/lanemask_in_1s_and_0s
pynast_template_alignment_fp	/home/db/blastdb/qiime/core_set_aligned.imputed.fasta
seconds_to_sleep	2
torque_queue	friendlyq
jobs_to_start	14
cloud_environment	False
denoiser_min_per_core	50
python_exe_fp	python
temp_dir	/tmp/
blastall_fp	blastall
sc_queue	all.q
cluster_jobs_fp	/home/sbi6dap/programs/qiime/bin/start_parallel_jobs.py
assign_taxonomy_reference_seqs_fp	/home/db/blastdb/qiime/gg_12_10_otus/rep_set/97_otus.fasta
qiime_scripts_dir	/home/sbi6dap/programs/qiime/bin/
assign_taxonomy_id_to_taxonomy_fp	/home/db/blastdb/qiime/gg_12_10_otus/taxonomy/97_otu_taxonomy.txt

parameter file values:
alpha_diversity:metrics	chao1,observed_species,shannon
parallel:jobs_to_start	14

Input file md5 sums:
refseq.biom: 821b3d8a2569159effa5a7fcf647dbd1
sample_map.txt: 653e9f1b1da6cf551dbdae8d16329594

Executing commands.

# Alpha rarefaction command 
python /home/sbi6dap/programs/qiime/bin//multiple_rarefactions.py -i refseq.biom -m 10 -x 1000 -s 99 -o arare/rarefaction/ 



*** ERROR RAISED DURING STEP: Alpha rarefaction
Command run was:
 python /home/sbi6dap/programs/qiime/bin//multiple_rarefactions.py -i refseq.biom -m 10 -x 1000 -s 99 -o arare/rarefaction/ 
Command returned exit status: 1
Stdout:

Stderr
Traceback (most recent call last):
  File "/home/sbi6dap/programs/qiime/bin//multiple_rarefactions.py", line 98, in <module>
    main()
  File "/home/sbi6dap/programs/qiime/bin//multiple_rarefactions.py", line 94, in main
    subsample_f=subsample_f)
  File "/usr/lib/python2.7/dist-packages/qiime/rarefaction.py", line 120, in rarefy_to_files
    subsample_f=subsample_f)
  File "/usr/lib/python2.7/dist-packages/qiime/rarefaction.py", line 177, in get_rare_data
    otu_table = filter_samples_from_otu_table(otu_table, otu_table.SampleIds, seqs_per_sample, inf)
  File "/usr/lib/python2.7/dist-packages/qiime/filter.py", line 504, in filter_samples_from_otu_table
    return otu_table.filterSamples(filter_f)
  File "/usr/lib/python2.7/dist-packages/biom/table.py", line 577, in filterSamples
    raise TableException, "All samples were filtered out!"
biom.exception.TableException: All samples were filtered out!


Logging stopped at 17:00:38 on 07 Mar 2014
